services:
  backend:
    platform: linux/arm64
    image: jtuongdev/mern-backend:1.0
    container_name: mern-backend-hub
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb+srv://Quanlysinhvien:mongo123@cluster0.owzc2fi.mongodb.net/?appName=Cluster0
    networks:
      - mern-network

  frontend:
    image: jtuongdev/mern-frontend:2.0
    container_name: mern-frontend-hub
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
